import "./styles/bootstrap.min.css";
import "./styles/font-awesome.css";
import "./styles/animate.css";
import "./styles/magnific-popup.css";
import "./styles/meanmenu.css";
import "./styles/slick.css";
import "./styles/swiper-bundle.min.css";
import "./styles/nice-select.css";
import "./styles/main.css";
import "./globals.css";
import Preloader from "@/layouts/Preloader";

export const metadata = {
  title: "CheetahNet - Internet Provider and Broadband TV React NextJS Template",
  description:
    "Generated by CheetahNet - Internet Provider and Broadband TV React NextJS Template",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Preloader />
        {children}
      </body>
    </html>
  );
}
